const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  USER: 'USER',
};

const ROLE_HIERARCHY = {
  SUPER_ADMIN: 4,
  ADMIN: 3,
  MANAGER: 2,
  USER: 1,
};

const PERMISSIONS = {
  TENANT_READ: 'tenant:read',
  TENANT_CREATE: 'tenant:create',
  TENANT_UPDATE: 'tenant:update',
  TENANT_DELETE: 'tenant:delete',
  USER_READ: 'user:read',
  USER_CREATE: 'user:create',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_INVITE: 'user:invite',
  SUBSCRIPTION_READ: 'subscription:read',
  SUBSCRIPTION_UPDATE: 'subscription:update',
  FEATURE_FLAG_READ: 'feature_flag:read',
  FEATURE_FLAG_UPDATE: 'feature_flag:update',
  ANALYTICS_READ: 'analytics:read',
  AUDIT_LOG_READ: 'audit_log:read',
};

const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.TENANT_READ, PERMISSIONS.TENANT_UPDATE,
    PERMISSIONS.USER_READ, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE, PERMISSIONS.USER_INVITE,
    PERMISSIONS.SUBSCRIPTION_READ, PERMISSIONS.SUBSCRIPTION_UPDATE,
    PERMISSIONS.FEATURE_FLAG_READ, PERMISSIONS.FEATURE_FLAG_UPDATE,
    PERMISSIONS.ANALYTICS_READ, PERMISSIONS.AUDIT_LOG_READ,
  ],
  MANAGER: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.USER_READ, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE, PERMISSIONS.USER_INVITE,
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.FEATURE_FLAG_READ,
    PERMISSIONS.ANALYTICS_READ, PERMISSIONS.AUDIT_LOG_READ,
  ],
  USER: [
    PERMISSIONS.TENANT_READ, PERMISSIONS.USER_READ,
    PERMISSIONS.SUBSCRIPTION_READ, PERMISSIONS.FEATURE_FLAG_READ, PERMISSIONS.ANALYTICS_READ,
  ],
};

function hasPermission(role, permission) {
  return (ROLE_PERMISSIONS[role] || []).includes(permission);
}

function hasMinRole(userRole, requiredRole) {
  return (ROLE_HIERARCHY[userRole] || 0) >= (ROLE_HIERARCHY[requiredRole] || 0);
}

module.exports = { ROLES, PERMISSIONS, ROLE_PERMISSIONS, ROLE_HIERARCHY, hasPermission, hasMinRole };
